export { default as BackdropRows } from "./BackdropRows";
export { default as PopularMovies } from "./PopularMovies";
export { default as PopularTv } from "./PopularTv";
export { default as Recommended } from "./Recommended";
export { default as Similar } from "./Similar";
export { default as TopRated } from "./TopRated";
export { default as MovieSlider } from "./MovieSlider";
export { default as Upcoming } from "./Upcoming";
export { default as Trending } from "./Trending";
